-- USE ROLE ACCOUNTADMIN for the initial setup
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS FINOPS_TRANSFORMER_ROLE;

USE ROLE SECURITYADMIN;
CREATE USER IF NOT EXISTS FINOPS_DBT_USER 
    PASSWORD = 'Snowflake022026'
    DEFAULT_ROLE = FINOPS_TRANSFORMER_ROLE;

GRANT ROLE FINOPS_TRANSFORMER_ROLE TO USER FINOPS_DBT_USER;

USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS FINOPS_WH 
    WAREHOUSE_SIZE = 'XSMALL' 
    AUTO_SUSPEND = 60 
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS FINOPS_DEV;
CREATE DATABASE IF NOT EXISTS FINOPS_PROD;

GRANT USAGE ON WAREHOUSE FINOPS_WH TO ROLE FINOPS_TRANSFORMER_ROLE;
GRANT ALL ON DATABASE FINOPS_DEV TO ROLE FINOPS_TRANSFORMER_ROLE;
GRANT ALL ON DATABASE FINOPS_PROD TO ROLE FINOPS_TRANSFORMER_ROLE;

-- The Gold Mine: Accessing Snowflake's own usage data
USE ROLE ACCOUNTADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE FINOPS_TRANSFORMER_ROLE;